### ISSUE TITLE
Extended Timeline no longer compatible

### ISSUE THREAD

**Issue by thecosmicslug** [thecosmicslug/Theatrum-Orbis-Terrarum#13]
Leaves a funky looking map outline.

Rexil from steam thinks colormap_*.dds  causes the double map and compatibility issues with ET. Worth testing again to stop the endless ET requests

here is another compatibility fix for ET for reference.
https://steamcommunity.com/linkfilter/?url=http://(https://steamcommunity.com/sharedfiles/filedetails/?id=1873032024)

**Comment by CarbonY26** [comment]
Qweytr in his discord suggests that compatibility with ET might have to be a separate mod.

**Comment by thecosmicslug** [comment]
it looks like its the water mods that are causing the misplaced provinces, ToT & ET seem to work fine but the water looks awful (vanilla).

Will keep investigating

**Comment by thecosmicslug** [comment]
OK the problem seems to be with either 'colormap_water.dds' or 'reflection.dds' I will have to investigate further

**Comment by thecosmicslug** [comment]
Its definitely the colormaps, they are different dimensions and trying to resize ToTs version just makes the provinces etc distorted. Starting to slowly transfer ToT map onto the ET colormaps, its slow but seems to be working so far. If all goes well I should be able to release a small compatibility patch for them both to play nice
