### ISSUE TITLE
Incompatible with extended timeline mod

### ISSUE THREAD

**Issue by OwenOnPC** [thecosmicslug/Theatrum-Orbis-Terrarum#2]
I know that on Kyro's original Theatrum Orbis Terrarum steam page, he advertised the mod as being compatible with extended timeline, however with the latest version of extended timeline, and your mod, the graphics are bugged. Oceans look strange and the terrain too. Nothing like how they should. I hope it's not too hard to make them work together, my favourite graphics mod!

**Comment by thecosmicslug** [comment]
I remember this happening with the 1.29 update.. it was fixed with an update to extended timeline, and nothing was changed this end. Like you say, they are normally compatible.

**Comment by thecosmicslug** [comment]
No response, Closing this for now
